# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-10 10:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_category_is_expended'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(blank=True, max_length=200, null=True, verbose_name='Seller Province')),
                ('location_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Seller Location')),
            ],
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='cell',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Phone Number'),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Seller Email'),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='province_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Location'),
        ),
    ]
