# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-10 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20170810_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='province',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Province'),
        ),
    ]
