# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-11 06:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20170810_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='facebook',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Facebook Username'),
        ),
        migrations.AddField(
            model_name='product',
            name='skype',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Skype Username'),
        ),
        migrations.AddField(
            model_name='product',
            name='twitter',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Twitter username'),
        ),
        migrations.AddField(
            model_name='product',
            name='watsapp',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Watsapp Number'),
        ),
    ]
